/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.2.1-17-g48ae235848"
#endif /* AVUTIL_FFVERSION_H */
